name: Parkalot Booking Bot

on:
  workflow_dispatch:

jobs:
  booking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run booking bot
        env:
          PARKALOT_EMAIL: ${{ secrets.PARKALOT_EMAIL }}
          PARKALOT_PASSWORD: ${{ secrets.PARKALOT_PASSWORD }}
        run: python booking_bot.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: booking-screenshots
          path: screenshots/
