- name: Install Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip curl
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)

          echo "Installed Chrome version: $CHROME_VERSION"
          echo "Fetching latest ChromeDriver for major version $MAJOR_VERSION"

          DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${MAJOR_VERSION}")
          echo "ChromeDriver version: $DRIVER_URL"

          wget https://storage.googleapis.com/chrome-for-testing-public/${DRIVER_URL}/linux64/chromedriver-linux64.zip -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          google-chrome --version
          chromedriver --version
