name: booking

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"
          pip install selenium webdriver-manager

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1 || echo "138")
          echo "Detected Chrome major version: $CHROME_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" -O LATEST_RELEASE
          DRIVER_VERSION=$(cat LATEST_RELEASE)
          wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver.zip
          unzip chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Debug Secrets
        run: |
          if [ -z "${{ secrets.EMAIL }}" ]; then echo "EMAIL secret is NOT set"; else echo "EMAIL secret is set"; fi
          if [ -z "${{ secrets.PASSWORD }}" ]; then echo "PASSWORD secret is NOT set"; else echo "PASSWORD secret is set"; fi

      - name: Run booking bot
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          mkdir -p screenshots
          python booking_bot.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: booking-screenshots
          path: screenshots/
