name: booking

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Install Chrome and matching ChromeDriver
        run: |
          set -e
          sudo apt update
          sudo apt install -y wget unzip xvfb google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
          echo "Detected Chrome major version: $CHROME_VERSION"

          # Function to download matching chromedriver
          download_driver() {
            DRIVER_VERSION=$1
            echo "Attempting ChromeDriver version: $DRIVER_VERSION"
            wget -q --continue -P /tmp "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip" \
            && unzip -o /tmp/chromedriver-linux64.zip -d /tmp/ \
            && sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver \
            && sudo chmod +x /usr/local/bin/chromedriver \
            && return 0
            return 1
          }

          # Try exact version
          if ! download_driver "${CHROME_VERSION}.0.7204.168"; then
            echo "Exact match not found. Trying ChromeDriver 114..."
            download_driver "114.0.5735.90" || (echo "No ChromeDriver worked!" && exit 1)
          fi

          chromedriver --version

      - name: Run booking bot
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          mkdir -p screenshots
          python booking_bot.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: booking-screenshots
          path: screenshots/
