name: Run Booking Bot
on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: "10 20 * * 0"  # Run at 20:10 UTC = 21:10 BST every Sunday
jobs:
  booking:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      # --- STEP 1: Checkout Repository ---
      - name: Checkout repository
        uses: actions/checkout@v4
      # --- STEP 2: Set Up Python ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      # --- STEP 3: Install Dependencies ---
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium python-dotenv chromedriver-autoinstaller
      # --- STEP 4: Debug Secrets ---
      - name: Debug Secrets
        run: |
          if [ -z "$EMAIL" ]; then
            echo "::error::EMAIL is not set!"
            exit 1
          fi
          if [ -z "$PASSWORD" ]; then
            echo "::error::PASSWORD is not set!"
            exit 1
          fi
          echo "[DEBUG] EMAIL and PASSWORD are set (hidden)."
      # --- STEP 5: Run Booking Bot ---
      - name: Run booking bot
        run: |
          mkdir -p screenshots
          for i in {1..3}; do
            python booking_bot.py 2>&1 | tee booking_bot.log && break
            echo "Attempt $i failed, retrying..."
            sleep 10
          done
        continue-on-error: true
      # --- STEP 6: Upload Screenshots ---
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: booking-screenshots
          path: screenshots/
          if-no-files-found: warn
      # --- STEP 7: Upload Log ---
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: booking-bot-log
          path: |
            booking_bot.log
            screenshots/*.html
            logs/*.log
