import os
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options

EMAIL = os.getenv("EMAIL")
PASSWORD = os.getenv("PASSWORD")

def init_driver():
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    return webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)

def login(driver):
    driver.get("https://app.parkalot.io")
    print("[DEBUG] Opening Parkalot website...")

    if not EMAIL or not PASSWORD:
        print("[DEBUG] Email set? NO")
        print("[DEBUG] Password set? NO")
        raise Exception("EMAIL or PASSWORD is not set. Exiting.")
    else:
        print("[DEBUG] Email set? YES")
        print("[DEBUG] Password set? YES")

    try:
        email_input = driver.find_element(By.NAME, "email")
        password_input = driver.find_element(By.NAME, "password")
        email_input.send_keys(EMAIL)
        password_input.send_keys(PASSWORD)
        driver.find_element(By.XPATH, "//button[contains(text(), 'LOG IN')]").click()
        time.sleep(5)
        print("[DEBUG] Login attempted.")
    except Exception as e:
        raise Exception(f"Login failed: {str(e)}")

def main():
    driver = init_driver()
    try:
        login(driver)
        print("[DEBUG] Successfully reached login process.")
        driver.save_screenshot("screenshots/step_login.png")
    finally:
        driver.quit()
        print("[DEBUG] Browser closed.")

if __name__ == "__main__":
    main()
