name: Parkalot Booking Bot

on:
  workflow_dispatch:

jobs:
  booking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb google-chrome-stable
          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "Detected Chrome version: $CHROME_VERSION"
          # Try multiple ChromeDriver versions
          for ver in 138.0.7204 114.0.5735; do
            echo "Trying ChromeDriver version $ver"
            wget -q --show-progress --progress=bar:force:noscroll \
              "https://storage.googleapis.com/chrome-for-testing-public/$ver/linux64/chromedriver-linux64.zip" \
              -O chromedriver.zip || continue
            unzip -o chromedriver.zip
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver
            rm -rf chromedriver.zip chromedriver-linux64
            break
          done
          chromedriver --version

      - name: Run booking bot
        run: |
          python booking_bot.py

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: booking-screenshots
          path: screenshots/
