name: Parking Booking at 20:00 BST
on:
  schedule:
    - cron: "0 19 * * *"  # 19:00 UTC = 20:00 BST
  push:  # Optional: Run on push for testing
    branches:
      - main
jobs:
  book-parking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager chromedriver-autoinstaller python-dotenv
      - name: Run booking script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python booking_script.py
      - name: Upload screenshots
        if: always()  # Upload even on failure
        uses: actions/upload-artifact@v4
        with:
          name: booking-screenshots
          path: screenshots/
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: booking-bot-log
          path: screenshots/*.html
